services:
  aw-customer:
    image: postgres:15
    container_name: aw-customerdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: customerdb
    ports:
      - "5442:5432"
    volumes:
      - aw-customer-data:/var/lib/postgresql/data
      - ./db/seed:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d customerdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  aw-internal:
    image: postgres:15
    container_name: aw-internaldb
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: internaldb
    ports:
      - "5444:5432"
    volumes:
      - aw-internal-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d internaldb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  aw-customer-data:
    driver: local
  aw-internal-data:
    driver: local
